name: Copy to OSS
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install && Build
      run: |
        npm install
        npm run build

    - name: OSS
      uses: manyuanrong/setup-ossutil@v1.0
      with:
        endpoint: "oss-cn-hangzhou.aliyuncs.com"
        access-key-id: ${{secrets.AccessKey_ID}}
        access-key-secret: ${{secrets.Access_Key_Secret}}
    - run: ossutil cp -rf dist oss://jx3box-www/$repo
 